<a href="https://colab.research.google.com/github/calistojuupiter-collab/sic_ai_2025_sept/blob/main/EJ1_Grupo2_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### SAMSUNG INNOVATION CAMPUS - CURSO INTELIGENCIA ARTIFICIAL
#### CAPÍTULO 3 :
### __ANÁLISIS EXPLORATORIO DE DATOS: NumPy Arrays para Cálculo Numérico Optimizado y Pandas__

[ESP SIC_AI_Chapter 3.pdf](https://drive.google.com/drive/folders/1U-qnwGcFqv9VVB3seJiS7J7aAZVCSlnd)


Comentarios y observaciones #EQUIPO 2 💛 __Páginas 76 -106__



UNIDAD 1
## __Estructura de datos de matriz NumPy para un rendimiento computacional óptimo.__
### 1.3. Operaciones de matriz Numpy




> En la matriz en NumPy los datos pueden procesarse colectivamente, gracias a la vectorización de la información, esto potencia el rendimiento  




In [ ]:
import numpy as np

In [ ]:
# LISTAS PARA EJEMPLOS

list1 = [1,2,3,4,5,6,7,8]
list2 = [5,10,15,20,25,30,35,40]

# ARRAYS DE NUMPY PARA EJEMPLOS

arr1
ar

In [ ]:
# Comparación de listas Python con matrices Numpy: Operador +  [Pág 77 - 78]
a=
b=
print(f"Esto es una suma de listas \n{a+b}")
arr1=np.array([1,2,3,4,5])
arr2=np.array([3,9,27,81,729])
print(f"\nEsto es una suma de arrays \n{arr1+arr2}")


Esto es una suma de listas 
[1, 2, 3, 4, 5, 6, 7, 8, 5, 10, 15, 20, 25, 30, 35, 40]

Esto es una suma de arrays 
[  4  11  30  85 734]


In [ ]:
# Operadores de suma, resta, multiplicación y división con matrices y igual dimensión [Pág 79]

"""
Primero se compara si ambos arrays son iguales
"""
print(f"Comparación ndim entre matrices {arr1.ndim , arr2.ndim}")
print(f"Comparación size entre matrices {arr1.size , arr2.size}")
print(f"Comparación shape entre matrices {arr1.shape , arr2.shape}")
print("")


# Operadores entre matrices
print(f"Sume de matrices            :  {arr1+arr2}")
print(f"Resta de matrices           :  {arr1-arr2}")
print(f"Multiplicación de matrices  :  {arr1*arr2}")
print(f"Divisiones de matrices      :  {arr1/arr2}")


Comparación ndim entre matrices (1, 1)
Comparación size entre matrices (5, 5)
Comparación shape entre matrices ((5,), (5,))

Sume de matrices            :  [  4  11  30  85 734]
Resta de matrices           :  [  -2   -7  -24  -77 -724]
Multiplicación de matrices  :  [   3   18   81  324 3645]
Divisiones de matrices      :  [0.33333333 0.22222222 0.11111111 0.04938272 0.00685871]


In [ ]:
# Comparación de listas Python con matrices Numpy: Muiltiplicación  [Pág 80]
print(f"Esto es una multiplicación de lista * una variable \n{a*3}")
print(" 🔹NOTA: al multuplicar una lista por una variable n, esta se repite n veces")

print(f"\nEsto es una multiplicación de un array * una variable \n{arr1*3}")


Esto es una multiplicación de lista * una variable 
[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]
 🔹NOTA: al multuplicar una lista por una variable n, esta se repite n veces

Esto es una multiplicación de un array * una variable 
[ 3  6  9 12 15]


In [ ]:
# Repetir y mosaico [Pág 81]
print(f"Esto es un array con repeat [3 veces] :  \n{np.repeat(arr1,3)}")
print("🔹NOTA: Al aplicar repear, los valores se repiten consecutivamente")

print(f"\nEsto es un array con tile [3 veces]   :  \n{np.tile(arr1,3)}")
print("🔹NOTA: Al aplicar tile, la matriz se repetira consecutivamente")

Esto es un array con repeat [3 veces] :  
[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]
🔹NOTA: Al aplicar repear, los valores se repiten consecutivamente

Esto es un array con tile [3 veces]   :  
[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]
🔹NOTA: Al aplicar tile, la matriz se repetira consecutivamente


In [ ]:
# Cuando se utliza el método de mosaico, la matriz se puede repetir de forma bidimensional [Pág 82]
arr3 = np.arange(15)
arr3 = arr3.reshape(3,5)

print(f"Esto es un array con tile [3 veces]: \n{np.tile(arr3,3)}")

Esto es un array con tile [3 veces]: 
[[ 0  1  2  3  4  0  1  2  3  4  0  1  2  3  4]
 [ 5  6  7  8  9  5  6  7  8  9  5  6  7  8  9]
 [10 11 12 13 14 10 11 12 13 14 10 11 12 13 14]]


In [ ]:
#Las matrices también pueden realizar operaciones exponenciales
arr2**2

NameError: name 'arr2' is not defined

In [ ]:


# Ralitza
# mosaico
c = np.arange(8).reshape(2, 4)
print(f"c={c}")
mosaico = np.tile(c, 2)
print(f"mosaico={mosaico}")

# exponencial
c = np.array([1, 2, 3, 4])
print(f"valor de c={c}")
d = c ** 2
print(f"valor de d={d}")
e = c / d
print(f"valor de e={e}")

# comparaciones
c = np.array([1, 2, 3, 4])
print(c > 0)
print(c < 0)

# funciones elemento por elemento
c = np.array([1, 2, 3, 4])
print(c ** 2)
print(np.sqrt(c))
print(np.sin(c))

# metodos estadisticos
c = np.arange(11)
print(c)
suma = c.sum()
print(f"suma={suma}")
promedio = c.mean()
print(f"promedio={promedio}")
desviacion = (c - promedio) ** 2
print(f"desviacion={desviacion}")
varianza = desviacion.sum() / c.size
print(f"varianza={varianza}")

# metodos estadisticos matrices
m = np.arange(1, 10).reshape(3, 3)
print(f"m={m}")
print(m.mean())
print(m.mean(axis=0))
print(m.mean(axis=1))
print(m ** 2)

## numeros aleatorios
np.random.seed(123) # iniciar la semilla de los nuevos aleatorios
print(f"random int={np.random.randint(0, 10)}") # genera  enteros de 0 a 10
print(f"random 3x3={np.random.randint(0, 10, size=(3, 3))}") # genera enteros de 0 a 10 en matriz de 3x3


In [ ]:
## Martina y Aracely

## martina
#Diapositivas 91- 93 Metodos estadísticos
import numpy as np
z = np.arange(4,20) #crea una matriz de una dimension desde el numero 4 hasta 20
#Calculos estadisticos
promedio=z.mean() #calcula el promedio de la matriz z a traves de la funcion mean
Desviacion= (z-promedio)** 2 #Se calcula la desviacion donde a la matriz z se le resta su promedio y esto se eleva a 2
Varianza= z.var()
Desviacion_estandar = np.sqrt(Varianza) # el metodo sqrt calcula la raiz cuadrada y en este caso al aplicarse a la varianza se calcula la desviacion estandar
Valores_acumulados_de_Z=z.cumsum() #calcula los valores acumulados de la matriz z

## aracely
## Diapositiva 88 - 90
#Primero, se crea un arreglo que contiene los números enteros del 1 al 10.
x = np.arange(1,11)
print(x)
#El código `x = np.arange(1, 11)` genera esa secuencia de números. La función arange crea números desde el primer valor (1) hasta uno antes del segundo valor (11). Este arreglo se almacena en la variable x.
x.sum() #Se utiliza para calcular la suma de todos los elementos que están dentro del arreglo x.
x.mean() #calcula el promedio (o media aritmetica) de los elementos en el arreglo.
x_mean=x.mean() #calcula el promedio del arreglo original x  y lo almacena en la variable x_mean para usarlo fácilmente en los siguientes pasos.
x-x_mean #calcula la desviación de cada dato. NumPy le resta el promedio (5.5) a cada uno de los elementos del arreglo original x.
#El resultado es un nuevo arreglo que nos dice qué tan lejos está cada número original del promedio.
(x-x_mean)**2 #Toma ese arreglo de desviaciones y eleva al cuadrado cada uno de sus elementos.
#Al elevar al cuadrado convertimos los valores negativos en positivos.
dev=(x-x_mean)**2 #Tomamos el calculo anterior y lo guardamos en una nueva variable llamada dev.
dev.sum() #Suma todos los valores que están en el arreglo dev




In [ ]:
# Fernanda
#la D77 :
lista_a = [1,2,3,4,5,6]
lista_b = [5,10,15,20,25,30]

c = lista_a + lista_b
c
# D78:
arr_1 = np.array([1,2,3,4,5,6])
arr_2 = np.array([5,10,15,20,25,30])

d = arr_1 + arr_2
d
# D79:
print(arr_1.ndim)
print(arr_1.size)
print(arr_1.shape)
# D80
display(lista_a*3)
display(arr_1*3)
# D81:
display(np.repeat(arr_1,5))
display(np.tile(arr_1,4))

In [ ]:
# Camila --- diapo 94 a la 99

a = np.arange(1, 19, 3)

# Definir dimensiones de matrices
print(a.reshape(2,3))
print(a.reshape(2,-1)) # -1, def automaticamente la cantidad necesaria de cols
a = a.reshape(2,3)

# Estadística

# promedio
print(a.mean(axis=0)) # para cols
print(a.mean(axis=1)) # para filas

# eligiendo una semilla
b = np.random.seed(13)

# generando números aleatorios
print(np.random.randint(8))
print(np.random.randint(13,27))

# confirmando semilla
while True:
  num = np.random.randint(13,27)
  print(num)
  if (num==15):
    break


In [ ]:
# Antonia
#Resumen final 101
np.random.seed(130)
print(f"""con la funcion randit podemos generar numero aleatorios segun un tamaño determinado \n en este caso crearremos numero aleatorios del 1 al 10 de un largo de 100""")

a=np.random.randint(1,11,size=100)
print(f"vector de 1000 elementos con numero del 1 al 10 \n",a)
print("###"*20)

a1 = np.random.randint(1,11,size=(4,4))
print(f"genera una matriz 4*4 con numero aleatorios \n",a1)
print("###"*20)
a2= np.random.randint(1,11,size=(4,4,4))
print(f"genera una matriz tridimencional 4*4*4 con numero aleatorios \n",a2)
print(f"el tamaño de nuestro primer ejemplo es:",a.size)
print(f"los numero que encontraremos en el primer ejempo:",np.unique(a))
print(f"la media de nuestro ejemplo es:", np.median(a))
print(f"la suma total de nuestro ejemplo es:", np.sum(a))
print(f"La media de nuestro ejemplo es: ", np.round(np.mean(a), 2))
print(f"La varianza de nuestro ejemplo es:", np.round(np.var(a), 2))
print(f"La desviación estándar de nuestro ejemplo es: ",np.round(np.std(a), 2))
print(f"El mínimo de nuestro ejemplo es:", a.min())
print(f"El máximo de nuestro ejemplo es:",a.max())
a=np.random.randint(-10,11,size=100)
print("\nVector de 100 elementos con números del -10 al 10:\n", a)
print(f"Los números únicos en este ejemplo son:",np.unique(a))
print(f"La ubicación del índice con el valor más alto es:",a.argmax())
print(f"La ubicación del índice con el valor más bajo es:", a.argmin())