<a href="https://colab.research.google.com/github/itscarop-ui/sic_ai_2025_sept/blob/main/2_preprocesamiento/contribuciones_estudiantes/archivo_prueba_jajaja.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.asmatrix('1 1; 1 1')
B = np.asmatrix('2 2; 2 2')
C = np.asmatrix('3 4; 5 6')
D = np.asmatrix('7 8; 9 0')

# 1. Con lista anidada
print(np.bmat([[A, B], [C, D]]))

# 2. Usando np.r_ y np.c_
print(np.bmat(np.r_[np.c_[A, B], np.c_[C, D]]))

# 3. Usando string
print(np.bmat('A,B; C,D'))


[[1 1 2 2]
 [1 1 2 2]
 [3 4 7 8]
 [5 6 9 0]]
[[1 1 2 2]
 [1 1 2 2]
 [3 4 7 8]
 [5 6 9 0]]
[[1 1 2 2]
 [1 1 2 2]
 [3 4 7 8]
 [5 6 9 0]]


In [ ]:
### jeanmelys navarro