<a href="https://colab.research.google.com/github/calistojuupiter-collab/sic_ai_2025_sept/blob/main/2_preprocesamiento/contribuciones_estudiantes/EJ1_SICAI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### SAMSUNG INNOVATION CAMPUS - CURSO INTELIGENCIA ARTIFICIAL
#### CAPÍTULO 3 :
### __ANÁLISIS EXPLORATORIO DE DATOS: NumPy Arrays para Cálculo Numérico Optimizado y Pandas__

[ESP SIC_AI_Chapter 3.pdf](https://drive.google.com/drive/folders/1U-qnwGcFqv9VVB3seJiS7J7aAZVCSlnd)


Comentarios y observaciones #EQUIPO 2 💛 __Páginas 76 -106__



UNIDAD 1
## __Estructura de datos de matriz NumPy para un rendimiento computacional óptimo.__
### 1.3. Operaciones de matriz Numpy




> En la matriz en NumPy los datos pueden procesarse colectivamente, gracias a la vectorización de la información, esto potencia el rendimiento  




In [ ]:
import numpy as np

In [ ]:
# LISTAS PARA EJEMPLOS

list1 = [1,2,3,4,5,6,7,8]
list2 = [5,10,15,20,25,30,35,40]

# ARRAYS DE NUMPY PARA EJEMPLOS

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,9,27,81,729])


In [ ]:
# Comparación de listas Python con matrices Numpy: Operador +  [Pág 77 - 78]

A1 = list1 + list2
A2 = arr1 + arr2

print(f"Esto es una suma de listas \n{A1}")

print(f"\nEsto es una suma de arrays \n{A2}")


Esto es una suma de listas 
[1, 2, 3, 4, 5, 6, 7, 8, 5, 10, 15, 20, 25, 30, 35, 40]

Esto es una suma de arrays 
[  4  11  30  85 734]


In [ ]:
# Operadores de suma, resta, multiplicación y división con matrices y igual dimensión [Pág 79]

"""
Primero se compara si ambos arrays son iguales
"""
print(f"Comparación ndim entre matrices {arr1.ndim , arr2.ndim}")
print(f"Comparación size entre matrices {arr1.size , arr2.size}")
print(f"Comparación shape entre matrices {arr1.shape , arr2.shape}")
print("")

B1 = arr1 + arr2
B2 = arr1 - arr2
B3 = arr1 * arr2
B4 = arr1 / arr2

# Operadores entre matrices
print(f"Sume de matrices            :  {B1}")
print(f"Resta de matrices           :  {B2}")
print(f"Multiplicación de matrices  :  {B3}")
print(f"Divisiones de matrices      :  {B2}")


Comparación ndim entre matrices (1, 1)
Comparación size entre matrices (5, 5)
Comparación shape entre matrices ((5,), (5,))

Sume de matrices            :  [  4  11  30  85 734]
Resta de matrices           :  [  -2   -7  -24  -77 -724]
Multiplicación de matrices  :  [   3   18   81  324 3645]
Divisiones de matrices      :  [  -2   -7  -24  -77 -724]


In [ ]:
# Comparación de listas Python con matrices Numpy: Muiltiplicación  [Pág 80]

C1 = list1 * 1
C2 = arr1 * 3

print(f"Esto es una multiplicación de lista * una variable \n{C1}")
print(" 🔹NOTA: al multuplicar una lista por una variable n, esta se repite n veces")

print(f"\nEsto es una multiplicación de un array * una variable \n{C2}")


Esto es una multiplicación de lista * una variable 
[1, 2, 3, 4, 5, 6, 7, 8]
 🔹NOTA: al multuplicar una lista por una variable n, esta se repite n veces

Esto es una multiplicación de un array * una variable 
[ 3  6  9 12 15]


In [ ]:
# Repetir y mosaico [Pág 81]

D1 = np.repeat(list1,3)
D2 = np.tile(list1,3)

print(f"Esto es un array con repeat [3 veces] :  \n{D1}")
print("🔹NOTA: Al aplicar repear, los valores se repiten consecutivamente")

print(f"\nEsto es un array con tile [3 veces]   :  \n{D2}")
print("🔹NOTA: Al aplicar tile, la matriz se repetira consecutivamente")

Esto es un array con repeat [3 veces] :  
[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6 7 7 7 8 8 8]
🔹NOTA: Al aplicar repear, los valores se repiten consecutivamente

Esto es un array con tile [3 veces]   :  
[1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]
🔹NOTA: Al aplicar tile, la matriz se repetira consecutivamente


In [ ]:
# Cuando se utliza el método de mosaico, la matriz se puede repetir de forma bidimensional [Pág 82]

arr3 = np.arange(15)
arr3 = arr3.reshape(3,5)

E1 = np.tile(arr3,3)

print(f"Esto es un array con tile [3 veces]: \n{E1}")

Esto es un array con tile [3 veces]: 
[[ 0  1  2  3  4  0  1  2  3  4  0  1  2  3  4]
 [ 5  6  7  8  9  5  6  7  8  9  5  6  7  8  9]
 [10 11 12 13 14 10 11 12 13 14 10 11 12 13 14]]


In [ ]:
# Las matrices también pueden realizar operaciones exponenciales [Pág 83]

F1 = arr1 ** 2
F2 = arr1 / (arr2 ** 2)

print(f"Esto es un array elevado al cuadrado  :  {F1}")
print(f"Esto es array / array^2               :  {F2}")

Esto es un array elevado al cuadrado  :  [ 1  4  9 16 25]
Esto es array / array^2               :  [1.11111111e-01 2.46913580e-02 4.11522634e-03 6.09663161e-04
 9.40838212e-06]


In [ ]:
# La matriz tambien puede realizar operaciones de comparación [...], devuelve True si hay una coincidencia y False si no la hay. [Pág 84]

G1 = arr1 > 4
G2 = arr1 <= 3

print(f"Esto es el array original             :  {arr1}")
print(f"Aplicamos array > 4 y obtenemos       :  {G1}")
print(f"Aplicamos array <= 3 y obtenemos      :  {G2}")


Esto es el array original             :  [1 2 3 4 5]
Aplicamos array > 4 y obtenemos       :  [False False False False  True]
Aplicamos array <= 3 y obtenemos      :  [ True  True  True False False]


In [ ]:
# Funciones universales [Pág 85 - 87]
H1 = arr1**2
H2 = np.sqrt(H1)

print(f"Esto es un array elevado al cuadrado              :  \n{H1}")
print(f"Esto es la raíz cuadrada del resultado anterior   :  \n{H2}")


print("\n\n🔹NOTA: Para más detalles consultar np.ufunc")


"Otro ejemplo de funcion"
print(np.sin(c))



Esto es un array elevado al cuadrado              :  
[ 1  4  9 16 25]
Esto es la raíz cuadrada del resultado anterior   :  
[1. 2. 3. 4. 5.]


🔹NOTA: Para más detalles consultar np.ufunc


Link para revisar más funciones universales

["NUMPY Universal functions - ufunc"](https://numpy.org/doc/stable/reference/ufuncs.html)

In [ ]:
## Martina y Aracely

import numpy as np


In [ ]:
# Métodos estadísticos de las matrices NumPy [Pág 88-93]

arr4 = np.arange(1,41)
I1 = arr4.sum()
I2 = arr4.mean()
I3 = arr4.std()
I4 = arr4.var()

# Cálculo de la suma de la desviación
I5 = ( ((arr4-I2)**2).sum() ) / arr4.size
I6 = np.sqrt(I5)

# Suma acumulada
I7 = arr4.cumsum()          # PÁG [93]

print(f"Esto es el array original   :  \n{arr4}\n")
print(f"Suma del array                 : {I1}")
print(f"Promedio del array             : {I2}")
print(f"Desviación estándar del array  : {I3:.2f}")
print(f"Varianza del array             : {I4}")

print(f"\nCalculos paso a paso")
print(f"Desviación estandar del array  : {I5}")
print(f"Varianza (raiz de la desv. std): {I6:.2f}")

print(f"\nSuma acumulada del array      : \n{I7}")


Esto es el array original   :  
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]

Suma del array                 : 820
Promedio del array             : 20.5
Desviación estándar del array  : 11.54
Varianza del array             : 133.25

Calculos paso a paso
Desviación estandar del array  : 133.25
Varianza (raiz de la desv. std): 11.54

Suma acumulada del array      : 
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210 231 253 276 300 325 351 378 406 435 465 496 528 561 595 630 666
 703 741 780 820]


In [ ]:
## Pág 88 - 90
#Primero, se crea un arreglo que contiene los números enteros del 1 al 10.
x = np.arange(1,11)
print(x)
#El código `x = np.arange(1, 11)` genera esa secuencia de números. La función arange crea números desde el primer valor (1) hasta uno antes del segundo valor (11). Este arreglo se almacena en la variable x.
x.sum() #Se utiliza para calcular la suma de todos los elementos que están dentro del arreglo x.
x.mean() #calcula el promedio (o media aritmetica) de los elementos en el arreglo.
x_mean=x.mean() #calcula el promedio del arreglo original x  y lo almacena en la variable x_mean para usarlo fácilmente en los siguientes pasos.
x-x_mean #calcula la desviación de cada dato. NumPy le resta el promedio (5.5) a cada uno de los elementos del arreglo original x.
#El resultado es un nuevo arreglo que nos dice qué tan lejos está cada número original del promedio.
(x-x_mean)**2 #Toma ese arreglo de desviaciones y eleva al cuadrado cada uno de sus elementos.
#Al elevar al cuadrado convertimos los valores negativos en positivos.
dev=(x-x_mean)**2 #Tomamos el calculo anterior y lo guardamos en una nueva variable llamada dev.
dev.sum() #Suma todos los valores que están en el arreglo dev

In [ ]:
## MARTINA #Pág 91- 93

z = np.arange(4,20) #crea una matriz de una dimension desde el numero 4 hasta 20
#Calculos estadisticos
promedio=z.mean() #calcula el promedio de la matriz z a traves de la funcion mean
Desviacion= (z-promedio)** 2 #Se calcula la desviacion donde a la matriz z se le resta su promedio y esto se eleva a 2
Varianza= z.var()
Desviacion_estandar = np.sqrt(Varianza) # el metodo sqrt calcula la raiz cuadrada y en este caso al aplicarse a la varianza se calcula la desviacion estandar
Valores_acumulados_de_Z=z.cumsum() #calcula los valores acumulados de la matriz z

In [ ]:
# Métodos estadísticos de las matrices NumPy [Pág 94-95]

# Las funciones universales tambíen pueden usarse en las respectivas filas y columnas de una matriz

J1 = arr4.reshape(4,10)
# Al dar reshape a una lista matriz de datos , puedo hacerlo con los valores exactos,
# o definir ya sea las filas o las columnas y dejar como -1 el otro valor, para que sea calculados automaticamente

J2 = arr4.reshape(8,-1) # -1, def automaticamente la cantidad necesaria de cols
J3 = arr4.reshape(-1,5) # -1, def automaticamente la cantidad necesaria de filas

print(f"Esto es el array original en su nueva forma :  \n{J1}\n")

J4 = J1.mean(axis=0) # 0 para columnas
J5 = J1.mean(axis=1) # 1 para las filas

print(f"Promedio de las columnas del array :  {J4}")
print(f"Promedio de las filas del array    :  {J5}")


# Bucle que se detiene cuando el random = 15
while True:
  num = np.random.randint(13,27)
  print(num)
  if (num==15):
    break


Esto es el array original en su nueva forma :  
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]

Promedio de las columnas del array :  [16. 17. 18. 19. 20. 21. 22. 23. 24. 25.]
Promedio de las filas del array    :  [ 5.5 15.5 25.5 35.5]


In [ ]:
# Camila --- diapo 94 a la 99

a = np.arange(1, 19, 3)

# Definir dimensiones de matrices
print(a.reshape(2,3))
print(a.reshape(2,-1))
a = a.reshape(2,3)

# Estadística

# promedio
print(a.mean(axis=0)) # para cols
print(a.mean(axis=1)) # para filas

# eligiendo una semilla
b = np.random.seed(13)

# generando números aleatorios
print(np.random.randint(8))
print(np.random.randint(13,27))

# confirmando semilla


In [ ]:
# Numeros aleatorios en NumPy [96-99]

K1 = 626

np.random.seed(K1) # Para iniciar la semilla de los nuevos aleatorios

# En Python se los números inician en 0
# Además, al definir intervalos se incluye el valor inicla pero expcluyen el valor final
# "low inclusive" & "high exclusive" : Ejemplo: (10)  -> Desde el 0 al 9
#                                              (1,11) -> Desde el 1 al 10

K2 = np.random.randint(21)
K3 = np.random.randint(0, 10, size=(3, 3))

print(f"Entrega un random int (máx 20)= {K2}") # genera  enteros de 0 a 20
print(f"Entra una matriz random de 3x3= \n{K3}") # genera enteros de 0 a 10 en matriz de 3x3


Entrega un random int (máx 20)= 17
Entra una matriz random de 3x3= 
[[8 9 5]
 [6 9 4]
 [2 7 0]]


In [ ]:
# Antonia
#Resumen final 101

np.random.seed(130)
print(f"""con la funcion randit podemos generar numero aleatorios segun un tamaño determinado \n en este caso crearremos numero aleatorios del 1 al 10 de un largo de 100""")

a=np.random.randint(1,11,size=100)
print(f"vector de 1000 elementos con numero del 1 al 10 \n",a)
print("###"*20)

a1 = np.random.randint(1,11,size=(4,4))
print(f"genera una matriz 4*4 con numero aleatorios \n",a1)
print("###"*20)
a2= np.random.randint(1,11,size=(4,4,4))
print(f"genera una matriz tridimencional 4*4*4 con numero aleatorios \n",a2)
print(f"el tamaño de nuestro primer ejemplo es:",a.size)
print(f"los numero que encontraremos en el primer ejempo:",np.unique(a))
print(f"la media de nuestro ejemplo es:", np.median(a))
print(f"la suma total de nuestro ejemplo es:", np.sum(a))
print(f"La media de nuestro ejemplo es: ", np.round(np.mean(a), 2))
print(f"La varianza de nuestro ejemplo es:", np.round(np.var(a), 2))
print(f"La desviación estándar de nuestro ejemplo es: ",np.round(np.std(a), 2))
print(f"El mínimo de nuestro ejemplo es:", a.min())
print(f"El máximo de nuestro ejemplo es:",a.max())
a=np.random.randint(-10,11,size=100)
print("\nVector de 100 elementos con números del -10 al 10:\n", a)
print(f"Los números únicos en este ejemplo son:",np.unique(a))
print(f"La ubicación del índice con el valor más alto es:",a.argmax())
print(f"La ubicación del índice con el valor más bajo es:", a.argmin())

con la funcion randit podemos generar numero aleatorios segun un tamaño determinado 
 en este caso crearremos numero aleatorios del 1 al 10 de un largo de 100
vector de 1000 elementos con numero del 1 al 10 
 [10  6  4  2  1  7  9  8  1  6  8  2  7  2 10  8  3  2  5  9  3  3  2  3
  8  4  2  3  7  9  5  4  9  6  3 10  4  6  9  3  8  8  3  1  6  2  1  9
  4  1  5 10  3  9 10  2  5  7  6  8  6  6  4  4  2  2  3  6  6 10  8  3
  3  2  5  1  5  5  9  1  5  1  3 10  2  8  9  8 10  2  4  1  8  5  6  9
  5  8  1  6]
############################################################
genera una matriz 4*4 con numero aleatorios 
 [[ 4  3  9  9]
 [ 1  7  7  8]
 [ 9  9  5  3]
 [ 8 10  6  7]]
############################################################
genera una matriz tridimencional 4*4*4 con numero aleatorios 
 [[[ 7  7 10  2]
  [ 1  9  8  8]
  [ 1  8  1  3]
  [ 1  7  7  4]]

 [[ 8  6  2  9]
  [ 4  1  6  3]
  [ 6  9  4  7]
  [ 7  1  4  6]]

 [[ 2  7 10  7]
  [ 2  7  8  1]
  [ 5  8  4 10]
  [ 9  7  3  