Operaciones Matriciales

###Ejercicio 1

In [ ]:

import numpy as np
#El primero es el largo de la lista y el Segundo son la cantidad de lista que secciona
A = np.array([0, 1, 2, 3]).reshape(2,2)
B = np.array([1, 6, 2, 4]).reshape(2,2)
print("El primero es el largo de la lista y el Segundo son la cantidad de lista que secciona")
print(">>>>>>>>><<<<<<<<<")
print(f"matriz 1:\n{A}")
print(">>>>>>>>><<<<<<<<<")
print(f"matriz 2:\n{B}")
print(">>>>>>>>><<<<<<<<<")


El primero es el largo de la lista y el Segundo son la cantidad de lista que secciona
>>>>>>>>><<<<<<<<<
matriz 1:
[[0 1]
 [2 3]]
>>>>>>>>><<<<<<<<<
matriz 2:
[[1 6]
 [2 4]]
>>>>>>>>><<<<<<<<<


###Ejercicio 2
El np.dot() en NumPy se usa para calcular el producto punto de dos arreglos. En el contexto de matrices, se refiere a la multiplicación de matrices.

​Cuando multiplicas la matriz A por la matriz B (np.dot(A, B)), el resultado es una nueva matriz donde cada elemento se calcula de la siguiente manera:
​Se toma una fila de la matriz A.
​Se toma una columna de la matriz B.
​Se multiplican los elementos correspondientes de la fila y la columna, y luego se suman los resultados.
​Est
Este proceso se repite para cada combinación de filas de A y columnas de B para llenar la nueva matriz resultante. Es importante que el número de columnas de la primera matriz (A) sea igual al número de filas de la segunda matriz (B). Si no lo son, la multiplicación de matrices no se puede realizar.


In [ ]:
print(">>>>>>>>><<<<<<<<<")
print(f"matriz 1:\n{A}")
print(">>>>>>>>><<<<<<<<<")
print(f"matriz 2:\n{B}")
print(">>>>>>>>><<<<<<<<<")
print(">>>>>>>>><<<<<<<<<")
print("Dot 1 A.dot(B)")
print(A.dot(B))
print(">>>>>>>>><<<<<<<<<")
print("Dot 2 np.dot(A,B)")

print(np.dot(A,B))
print(">>>>>>>>><<<<<<<<<")


>>>>>>>>><<<<<<<<<
matriz 1:
[[0 1]
 [2 3]]
>>>>>>>>><<<<<<<<<
matriz 2:
[[1 6]
 [2 4]]
>>>>>>>>><<<<<<<<<
>>>>>>>>><<<<<<<<<
Dot 1 A.dot(B)
[[ 2  4]
 [ 8 24]]
>>>>>>>>><<<<<<<<<
Dot 2 np.dot(A,B)
[[ 2  4]
 [ 8 24]]
>>>>>>>>><<<<<<<<<




### Ejercicio 3


In [ ]:
print("Es la matriz transpuerta")
print("​La matriz transpuesta es el resultado de intercambiar las filas por las columnas")
A = np.array([0, 1, 2, 3]).reshape(2,2)
B = np.array([1, 6, 2, 4]).reshape(2,2)
print(">>>>>>>>><<<<<<<<<")
print("A")
print(A)
print(">>>>>>>>><<<<<<<<<")
print("B")
print(B)
print(">>>>>>>>><<<<<<<<<")
print("trans_1 = B.transpose()")
trans_1 = B.transpose()
print(">>>>>>>>><<<<<<<<<")
print(trans_1)


Es la matriz transpuerta
​La matriz transpuesta es el resultado de intercambiar las filas por las columnas
>>>>>>>>><<<<<<<<<
A
[[0 1]
 [2 3]]
>>>>>>>>><<<<<<<<<
B
[[1 6]
 [2 4]]
>>>>>>>>><<<<<<<<<
trans_1 = B.transpose()
>>>>>>>>><<<<<<<<<
[[1 2]
 [6 4]]


In [ ]:
print(">>>>>>>>><<<<<<<<<")
print("A")
print(A)
print(">>>>>>>>><<<<<<<<<")
print("B")
print(B)
print(">>>>>>>>><<<<<<<<<")
print("Inversa")
print(np.linalg.inv(A))
print(">>>>>>>>><<<<<<<<<")
print("Determinante")

print(np.linalg.det(A))

>>>>>>>>><<<<<<<<<
A
[[0 1]
 [2 3]]
>>>>>>>>><<<<<<<<<
B
[[1 6]
 [2 4]]
>>>>>>>>><<<<<<<<<
Inversa
[[-1.5  0.5]
 [ 1.   0. ]]
>>>>>>>>><<<<<<<<<
Determinante
-2.0
