<a href="https://colab.research.google.com/github/mariavanez/sic_ai_2025_sept/blob/main/2_preprocesamiento/contribuciones_estudiantes/GRUPO_1_PRESENTACI%C3%93N.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ÍNDICE

## 1. Números aleatorios. (62 - 68)
- Antonia Reyes (Slides 62-64).
- Montserrat Espinoza (Slides 65-67).
- María Añez (Slide 68).
## 2. Adición de elementos a Numpy (69 - 72)
- María Añez (Slide 69).
- Daniela Alarcón (Slides 70-72).
## 3. Eliminación de elementos de matrices Numpy. (73 - 74)
- Danna Villa (Slides 73-74).

PRESENTACIÓN:
https://drive.google.com/drive/folders/1U-qnwGcFqv9VVB3seJiS7J7aAZVCSlnd




# SLIDE 62-64. Números aleatorios con NumPy

In [ ]:
import numpy as np

data=np.random.randn(2,3)

**Explicación**

```
np.random.randn(100,100)
```
está en una distribución normal. Campana de Gauss.

Genera números aleatorios que siguen una distribución normal estándar
(media = 0, desviación estándar = 1).

El resultado es una matriz de 100 filas y 100 columnas (10,000 valores en total).


```
np.mean(data2)
```
Calcula el promedio de todos los 10,000 números generados.

Como la media teórica de la distribución normal estándar es 0, el resultado es muy cercano a 0.

```
data2
```



Muestra la matriz generada (se imprime solo una parte porque es muy grande).

Idea clave

Con pocos números aleatorios, el promedio puede alejarse bastante de 0.

Con muchos números aleatorios (10,000 en este caso), el promedio se acerca mucho al valor esperado (0).

*Esto demuestra la Ley de los Grandes Números:*

Mientras más datos se generan, más se aproximan los resultados a los valores teóricos esperados.


In [ ]:
import numpy as np

data=np.random.randn(3,4) ## (número de filas, número de columnas)
print(data)
print(np.mean(data)) ## el promedio de todos los valores dentro de la matriz


[[-2.14293201  0.26120511 -0.82614061 -0.69726052]
 [ 0.53712036  0.37936657 -0.98005254  2.37106805]
 [ 0.43211999  2.29867943  0.23386184 -0.32979729]]
0.12810319833654446


In [ ]:
## ejemplo Datos 2
data2 = np.random.randn(100,100)

print('promedio:',np.mean(data2))
data2
## En total hay 10000 valores

promedio: 0.009848381488615962


array([[ 1.59552558, -2.21129338,  1.65553804, ..., -0.13102436,
        -1.75018706, -0.96134648],
       [-1.13769802, -0.56415956, -0.13604522, ...,  0.45201482,
        -0.2546302 ,  1.05291578],
       [ 1.27345287, -0.25626823,  1.69415198, ...,  0.70445794,
         1.6536671 ,  1.66779318],
       ...,
       [-2.16189141, -0.50646133, -0.80967149, ..., -1.43862151,
         1.63064028, -0.3116743 ],
       [ 0.01281206, -0.60853703, -0.10366321, ..., -0.40714168,
         0.22544711,  1.92078116],
       [-0.92745008, -0.06944664, -0.24278193, ..., -0.51303493,
        -0.61628055,  0.77571337]])

In [ ]:
## Ejemplo datos3
data3 = np.random.randn(1000,1000)

print('promedio:',np.mean(data3))
data3
## En total hay 1000000 valores


promedio: -0.00037824745223618975


array([[-0.26944819, -0.15217521, -0.98284389, ...,  0.4452991 ,
         1.60432252, -0.6703235 ],
       [-0.32711247,  0.1866937 ,  0.74677509, ..., -0.77557097,
         1.65755979, -1.22342766],
       [-0.74878716, -1.54326337,  0.44712455, ..., -0.21887001,
        -0.33710941, -1.37410426],
       ...,
       [ 0.16845514,  1.97797593, -1.21686073, ..., -0.49272072,
         1.2764578 ,  1.14337357],
       [ 1.70207208, -0.11244461, -0.27140431, ...,  1.13418252,
        -0.60998114, -1.14233482],
       [-0.89238339,  0.20228979,  0.86609976, ..., -0.1297339 ,
        -0.08991897, -0.84297909]])

# SLIDES 65-67. Comparacion de listas de Python vs Matrices Numpy. Velocidades de procesamiento (Parte 1 - Parte 3)

- Lista de Python: Es una forma básica de guardar muchos datos en Python

 ej:

 List (range(5)) → [0, 1, 2, 3, 4]


  - Arrays/Matrices en Numpy: Es parecida a la lista, pero más rápido para calculos númericos.

  ej:

  np.arange(1000000) → genera un millón de números del 0 al 999999.


## Principales diferencias:

Las listas son mas lentas porque pueden guardar cualquier cosa. Mientras que los array solo datos homogeneos (como solo números) y usan memoria optimizada.

Velocidad

Ejemplo de velocidad

Multiplicar un array de NumPy por 2: np.arange(1000000)*2 → tarda 2.69 segundos.

Multiplicar una lista de Python por 2: list(range(1000000))*2 → tarda 40.6 segundos.

¡Más de 20 veces más lento con listas!

# SLIDE 68. Comparativa de listas de Python frente a Matrices Numpy. Velocidad de procesamiento (Parte 4)






## 1.   Diferencia entre listas de Python y arrays de NumPy



En Python, cuando usas listas, las operaciones suelen hacerse con bucles:

In [2]:
# Con listas de Python
lista = [1, 2, 3, 4, 5]
doble = []
for i in lista:
    doble.append(i * 2)

print(doble)  # [2, 4, 6, 8, 10]

# Aquí el programa recorre elemento por elemento con un for, lo cual es lento.

[2, 4, 6, 8, 10]


Con NumPy, la operación se hace en una sola instrucción (vectorización):

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
doble = array * 2

print(doble)  # [ 2  4  6  8 10 ]

# NumPy internamente usa código en C optimizado, evitando el bucle en Python.

##2. Tiempo de ejecución ("tiempo de pared")



El tiempo de ejecución (o “tiempo de pared”) es el tiempo real que tarda un programa o un fragmento de código en ejecutarse desde que inicia hasta que termina.
Incluye:

- Tiempo de CPU 🖥️ (cálculos matemáticos).

- Tiempo de E/S (entrada/salida, por ejemplo leer del disco o mostrar en pantalla).

- Llamadas a funciones/subprogramas.

- En otras palabras, es lo que percibimos como tiempo total de espera.

In [6]:
import numpy as np
import time

# Listas en Python
lista = list(range(1_000_000))       # 1. Crear una lista con un millón de números
start = time.time()                  # 2. Guardar el tiempo de inicio
doble_lista = [x*2 for x in lista]   # 3. Recorrer la lista y multiplicar cada elemento
print("Tiempo con listas:", time.time() - start)  # 4. Calcular tiempo de ejecución


Tiempo con listas: 0.06225919723510742


¿Qué pasa en cada línea?

1. Crear la lista: Aquí Python reserva memoria y llena la lista con números de 0 a 999,999.

2. Guardar tiempo inicial: Tomamos un "reloj" en ese instante.

3. Multiplicación con bucle: Python recorre uno por uno los elementos y crea otra lista → aquí es donde más tiempo se gasta.

4. Tiempo final: Restamos el tiempo actual menos el inicial, obteniendo cuánto tardó el paso 3.

Ahora con NumPy:

In [7]:
array = np.arange(1_000_000)     # 1. Crear un array con un millón de números
start = time.time()              # 2. Guardar el tiempo de inicio
doble_array = array * 2          # 3. Multiplicar TODO el array a la vez (vectorización en C)
print("Tiempo con NumPy:", time.time() - start)  # 4. Tiempo total

Tiempo con NumPy: 0.003941059112548828


¿Qué pasa en cada línea?

1. Crear el array: Similar a la lista, pero se almacena en memoria contigua y en formato numérico optimizado.

2. Tiempo inicial: Igual que antes, empezamos a medir.

3. Vectorización: NumPy no hace un for, sino que manda la operación al núcleo en C, y multiplica todos los elementos de golpe → esto es muy rápido.

4. Tiempo final: Medimos cuánto tardó (muchísimo menor que con listas).

## 3. Vectorización sin bucles



La vectorización es una técnica en la que aplicamos operaciones matemáticas o lógicas a un conjunto de datos entero (vector, matriz, array) de una sola vez, en lugar de hacerlo elemento por elemento con un bucle.

En palabras simples: en vez de decirle a la computadora “multiplica el primero, después el segundo, después el tercero…”, le dices “multiplica todo el conjunto de una sola vez”.

Esto es posible porque librerías como NumPy internamente usan código en C optimizado y aprovechan instrucciones vectoriales de la CPU (SIMD).

- Vectorización con bucles (lo tradicional en Python)

In [1]:
# Multiplicar cada número de una lista por 2
lista = [1, 2, 3, 4, 5]
doble = []

for i in lista:         # Aquí usamos un bucle
    doble.append(i * 2)

print(doble)  # [2, 4, 6, 8, 10]


[2, 4, 6, 8, 10]


Aquí el programa repite la instrucción *2 para cada elemento. Esto es lento porque Python interpreta cada paso.

- Vectorización sin bucles (con NumPy)

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
doble = array * 2   # Sin bucles visibles

print(doble)  # [ 2  4  6  8 10 ]


- Vectorización en programación: aplicar operaciones a un conjunto completo de datos en paralelo (aprovechando CPU/GPU).

- Vectorización sin bucles: para el programador, no hay for o while; en cambio, se usa una sola instrucción (array * 2, a + b, etc.).

- Internamente, sí existen bucles, pero en C y hardware optimizado, muchísimo más rápidos que los bucles de Python.

## 4. Ejemplo en Machine Learning



Cuando entrenas un modelo, por ejemplo una regresión lineal, tienes que hacer operaciones con vectores y matrices.

En Python normal:

In [8]:
# Simulando pesos y características
x = [1, 2, 3, 4, 5]
w = [0.5, 0.2, 0.9, 1.1, 0.3]

# producto punto "a mano"
resultado = 0
for i in range(len(x)):
    resultado += x[i] * w[i]

print(resultado)


9.5


En NumPy:

In [9]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
w = np.array([0.5, 0.2, 0.9, 1.1, 0.3])

resultado = np.dot(x, w)
print(resultado)


9.5


Así es como aprendizaje automático usa NumPy para cálculos masivos de manera rápida.

# SLIDE 69. Adición de Elementos en Numpy

---

### 🔹 `np.array`

Es una función de **NumPy** (la librería de Python para cálculo numérico) que se usa para **crear un arreglo (array) de Numpy**.

Un `array` es similar a una lista de Python, pero mucho más eficiente para operaciones matemáticas porque todos los elementos tienen el **mismo tipo de dato** y NumPy puede aprovechar optimizaciones internas.

📌 Ejemplo:

```python
import numpy as np

# Crear un array a partir de una lista
arr = np.array([1, 2, 3, 4, 5])
print(arr)
# Resultado: [1 2 3 4 5]

# Crear un array bidimensional (matriz)
matriz = np.array([[1, 2], [3, 4]])
print(matriz)
# Resultado:
# [[1 2]
#  [3 4]]
```

---

### 🔹 `np.append`

Sirve para **añadir elementos a un array existente** y devuelve **un nuevo array** (los arrays de NumPy son inmutables en tamaño, así que en realidad no se modifica el original).

📌 Ejemplo 1: añadir un valor

```python
arr = np.array([1, 2, 3])
nuevo = np.append(arr, 4)
print(nuevo)  
# Resultado: [1 2 3 4]
```

📌 Ejemplo 2: añadir varios valores

```python
arr = np.array([1, 2, 3])
nuevo = np.append(arr, [4, 5, 6])
print(nuevo)
# Resultado: [1 2 3 4 5 6]
```

📌 Ejemplo 3: en matrices

```python
matriz = np.array([[1, 2], [3, 4]])
nueva = np.append(matriz, [[5, 6]], axis=0)  # agregar fila
print(nueva)
# Resultado:
# [[1 2]
#  [3 4]
#  [5 6]]
```

---

✅ En resumen:

* `np.array` 👉 crea un array de NumPy.
* `np.append` 👉 añade elementos a un array y devuelve uno nuevo.


# SLIDES 70-72. Conceptos básicos de NumPy Array



    ¿Qué es numpy.append()?

Es un método de NumPy que sirve para agregar valores a un arreglo (array) existente. A diferencia de las listas en Python, no se usa + para unir, sino este método.

    Si el array es 2D (matriz), debes indicar la dirección con el parámetro axis:

axis=0 → se agregan filas (extensión vertical).

axis=1 → se agregan columnas (extensión horizontal).

    np.append() devuelve un nuevo array, no modifica el original. Por eso, es importante que si quieres conservar el cambio, debes asignarlo a una variable.



*Array* original:

In [ ]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])
print(a)

[[1 2]
 [3 4]]


Agregamos una fila con axis=0: (Vertical)

In [ ]:
b = np.append(a, [[9, 9]], axis=0)
print(b)

[[1 2]
 [3 4]
 [9 9]]


Agregamos una fila con axis=1: (Horizontal)

> Agregar bloque entrecomillado



In [ ]:
c = np.append(a, [[9], [9]], axis=1)
print(c)

[[1 2 9]
 [3 4 9]]


# SLIDES 73-74. Eliminación de Elementos de Matrices Numpy