<a href="https://colab.research.google.com/github/Maria-Saldivia/sic_ai_2025_sept/blob/main/2_preprocesamiento/contribuciones_estudiantes/Grupo_5___3_ex_0103a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ¿Qué es un array de NumPy?

Un **array de NumPy** es una estructura de datos proporcionada por la biblioteca **NumPy** en Python. Está diseñado para trabajar de forma eficiente con **grandes volúmenes de datos numéricos**.

### 🧮 Características principales

- Es similar a una **lista** de Python, pero mucho más **eficiente** para operaciones matemáticas.
- Todos los elementos son del **mismo tipo de dato** (por ejemplo, todos `int` o todos `float`).
- Puede tener múltiples dimensiones:
  - 1D: Vector
  - 2D: Matriz
  - 3D o más: Tensor (usado en machine learning, deep learning, etc.)

---

### 📦 Ejemplo básico

```python
import numpy as np

# Crear un array de 1 dimensión
a = np.array([1, 2, 3, 4])

# Crear un array de 2 dimensiones (matriz)
b = np.array([[1, 2], [3, 4]])


In [ ]:
import numpy as np  #Importar la librería

In [ ]:
a = np.array([1, 2, 3, 4, 5])		# A one dimensional NumPy array. Que sería un VECTOR. Se crea un arreglo de una dimensión

In [ ]:
a[:3]							# From the index 0 up to the index 1 (excluding 2).  Muestra el dato que que se encuentra en el índice 0 y 1

array([1, 2, 3])

In [ ]:
a[-1] # Muestra el último número del arreglo

np.int64(5)

In [ ]:
a[:] #Muestra todo el arreglo ya que   Slicing: seleccionar por rangos.

array([1, 2, 3, 4, 5])

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])	# This is a 3 x 3 two dimensional array (matrix). Se crea una matriz de dos dimensiones de 3x3

In [ ]:
a[1]				# The row 1. FILA 1 COMPLETA

array([4, 5, 6])

In [ ]:
a[-1]				# The last row. ULTIMA FILA

array([7, 8, 9])

## 📌 `a[:]` en Python

`a[:]` es una operación de **slicing** (segmentación o corte) que selecciona **todos los elementos** de un array o lista, desde el primero hasta el último.

Se le puede agregar posiciones

In [ ]:
a[:]				# The whole array (matrix). TODA LA MATRIZ

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[:2]				# From the row 0 to the row 1 (excluding the row 2).

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a[2][1]			# The element from the row 2 and the column 1.

np.int64(8)

In [ ]:
a[2, 1]			# The same as above.

np.int64(8)

In [ ]:
a[[0, 2]]			# The rows 0 and 2.

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
a[1:, 1:]			# From the row 1 to the end. From the column 1 to the end.

array([[5, 6],
       [8, 9]])

## 🧠 Resumen: Filtrado de arrays con máscaras booleanas (NumPy)

### 📌 ¿Qué es una máscara booleana?
Una **máscara booleana** es un array de `True`/`False` que permite **filtrar elementos** de otro array usando condiciones lógicas.
Este método de acceso se conoce como **fancy indexing**.
---

### 🧪 Ejemplo

```python
import numpy as np

arr = np.arange(100)  # Array de 0 a 99

# 1. Múltiplos de 5
mask = (arr % 5 == 0)
arr[mask]

# 2. Múltiplos de 5 y mayores a 0
mask = ((arr % 5 == 0) & (arr > 0))
arr[mask]


In [ ]:
arr = np.arange(100)		# A sequence from 0 to 99.

In [ ]:
arrMask = ((arr % 5) == 0) 		# A Boolean array. True if multiple of 5, else False.

In [ ]:
arr[arrMask]			# Apply fancy indexing.

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
arrMask = ( ( (arr % 5) == 0 )  & ( arr >0) )	# A Boolean array. True if multiple of 5 or 0, else False.

In [ ]:
arr[arrMask]			# Apply fancy indexing.

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

## 🧠 Resumen: Boolean Indexing en NumPy

### 📌 ¿Qué es?
El **boolean indexing** permite filtrar elementos de un array usando una condición lógica que devuelve un array de `True`/`False`.

---

### 🧪 Ejemplo rápido

```python
test_a = np.array([1, 4, 0, 2, 3, 8, 9, 7])
test_a[test_a > 3]



In [ ]:
test_a = np.array([1,4,0,2,3,8,9,7])

In [ ]:
test_a

array([1, 4, 0, 2, 3, 8, 9, 7])

In [ ]:
#The boolean value for whether the value is greater or less than 3 among each element in test_a.

In [ ]:
test_a > 3  # Muestra el array pero mostrando si cumple o no la condición

array([False,  True, False, False, False,  True,  True,  True])

In [ ]:
test_a[test_a>3]

array([4, 8, 9, 7])

Slicing: seleccionar por rangos.

Fancy indexing: seleccionar usando listas o máscaras booleanas complejas.

Boolean indexing: filtrar directamente según condiciones lógicas.