<a href="https://colab.research.google.com/github/itscarop-ui/sic_ai_2025_sept/blob/main/2_preprocesamiento/contribuciones_estudiantes/grupo5_exx_4_ex_0103b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Array Transposition

In [ ]:
import numpy as np #Se importa la librería numpy con np como apodo para utilizarla más rápido

In [ ]:
arr=np.arange(15).reshape((3,5)) #Se crea una matriz de dos dimensiones de 3x5 con números del 0 al 14
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
arr.T # Con este código se traspone la matriz dejandola de 5x3

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [ ]:
arr=np.random.randn(6,3) #Se crea una matriz de dos dimensiones de 6x3 de forma aleatoria
arr

array([[-3.35641383,  1.43583814, -0.33053685],
       [ 0.21262748, -0.71802597,  0.43836546],
       [-0.82622727,  0.5809071 , -0.90938406],
       [-0.27439054,  0.25057169, -0.85785276],
       [-0.6183831 , -0.96436851, -1.15291873],
       [-1.9322816 ,  0.04208619,  0.64958165]])

In [ ]:
np.dot(arr.T, arr) # Multiplicación de la matriz traspuesta con la original creando una matriz de 3x3, se utiliza para ver la similitud entre la columna 0 y la columna 1

array([[16.18477571, -5.00562799,  1.64714238],
       [-5.00562799,  3.90920956, -0.39339954],
       [ 1.64714238, -0.39339954,  3.61548753]])

In [ ]:
arr=np.arange(16).reshape(2,2,4) # Crea una matriz tridimensional de 2x2x4 hasta la posición 15

In [ ]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
arr.transpose((1,0,2)) # Intercambia el eje 0 y el 1 entre ellos. Sigue quedando una matriz de 2x2x4

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [ ]:
arr # Imprime la matriz

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
arr.swapaxes(1,2) #Intercambia el eje 1 con el 2. útil en arrays de más de 2 dimensiones, cambiando la dimensión de la matriz, quedando en 4x4x2

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])